# Generated by Django 2.1.7 on 2019-06-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargestation',
            name='name',
        ),
        migrations.AddField(
            model_name='chargestation',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='chargestation',
            name='dealer',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='chargepoints',
            name='slots',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chargepoints',
            name='slots_occupied',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chargertype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
