# Generated by Django 2.2.1 on 2019-06-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0002_auto_20190601_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargestation',
            name='data',
            field=models.TextField(default='{\n    "wall": 0,\n    "j-1772": 0,\n    "CHAdeMO": 0,\n    "Tesla(roadster)": 0,\n    "NEMA 14-50": 0,\n    "Tesla": 0,\n    "Type-2": 0,\n    "Type-3": 0,\n    "wall(BS1361)": 0,\n    "Wall(euro)": 0,\n    "Commando": 0,\n    "wall(AU/NZ)": 0,\n    "Caravan Mains": 0,\n    "CCS/SAE": 0,\n    "THREEPhase": 0,\n\n    "wall-a": 0,\n    "j-1772-a": 0,\n    "CHAdeMO-a": 0,\n    "Tesla(roadster)-a": 0,\n    "NEMA 14-50-a": 0,\n    "Tesla-a": 0,\n    "Type-2-a": 0,\n    "Type-3-a": 0,\n    "wall(BS1361)-a": 0,\n    "Wall(euro)-a": 0,\n    "Commando-a": 0,\n    "wall(AU/NZ)-a": 0,\n    "Caravan Mains-a": 0,\n    "CCS/SAE-a": 0,\n    "THREEPhase-a": 0\n    }'),
        ),
    ]
