# Generated by Django 2.1.7 on 2019-03-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('details', models.TextField(blank=True, help_text='Save timetable here in json along with other details', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='school.ClassGroup')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schools', to='users.User2')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=15)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profiles', to='users.User2')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.School')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('time_alloted', models.PositiveIntegerField(default=0, help_text='Time alloted in minutes')),
                ('max_consecutive_time', models.PositiveIntegerField(default=0)),
                ('min_consecutive_time', models.PositiveIntegerField(default=0)),
                ('details', models.TextField(blank=True, null=True)),
                ('class_groups_assigned', models.ManyToManyField(related_name='subjects', to='school.ClassGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=15)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profiles', to='users.User2')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.School')),
            ],
        ),
        migrations.AddField(
            model_name='period',
            name='students_present',
            field=models.ManyToManyField(related_name='periods_attended', to='school.Student'),
        ),
        migrations.AddField(
            model_name='period',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='school.Subject'),
        ),
        migrations.AddField(
            model_name='period',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='school.Teacher'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='school.School'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='students',
            field=models.ManyToManyField(related_name='class_groups', to='school.Student'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='teacher_incharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_incharged_with', to='school.Teacher'),
        ),
    ]
